# Generated by Django 4.2.9 on 2024-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='images/placeholder-avatar.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(default='Name'),
        ),
    ]
